### PR TITLE
F/support more boolean strings

### LINKED ISSUE #60: Handle "False" or "True" as boolean values
The Esri python API passes in `'True'` and `'False'` for boolean parameters. Can you fix this to handle this variation in case?

https://github.com/koopjs/koop-core/blob/99d01c483f3e658bb37f474f65fc5d6af720a136/src/middleware/index.js#L34

### PR DESCRIPTION
**Pull request by haoliangyu**
* resolve #60 
* fix a silently failed test at ` test/index-test.js`
* add npm lockfile

### CODE REVIEW

**Comment by haoliangyu** [comment]
This should also fix https://github.com/koopjs/FeatureServer/issues/174.

**Comment by nheminger** [comment]
I made the same changes manually to a local install and this does appear to fix #174. Will test again later with an actual build.

**Comment by rgwozdz** [comment]
We haven't released to NPM yet, will do and notify you.

**Comment by rgwozdz** [comment]
Just published 3.16.0.

**Pull request merged**
